.\" Kai's Manpage Generator
.
.TH "SDKL" "1" "August 2021" "" ""
.
.SH "NAME"
\fBsdkl\fR \- A powerful language running on the Lua 5\.4 VM\.
.
.SH "SYNOPSIS"
\fBsdkl\fR [options] [file]
.
.SH "DESCRIPTION"
SDKL is a lightweight, powerful Scripting Language inspired off of the Lua 5\.4 Programming language\.
.
.P
SDKL is a different version of Lua, utilizing the source code, and building onto it\.
.
.SH "LIBRARIES"
.
.SS "io"
Contains basic functions for Lua I/O operations\.
.
.SS "string"
Contains basic functions for String operations\.
.
.SS "coroutine"
Contains basic functions for Coroutine operations\.
.
.SS "table"
Contains basic functions for Table manipulation operations\.
.
.SH "EXAMPLE LIBRARIES"
.
.SH "path"
Path library inspired off of Python3\'s \fBpathlib\fR
.
.SH "COPYRIGHT"
SDKL is licensed under the MIT license and any issues email Kai Gonzalez @ \fIgkai70264@gmail\.com\fR
