/*
** $Id: sdkl.c $
** SDKL stand-alone interpreter
** See Copyright Notice in sdkl.h
*/

#define sdkl_c

#include "lprefix.h"


#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <signal.h>

#include "sdkl.h"

#include "sdklauxillary.h"
#include "sdkllib.h"


#if !defined(SDKL_PROGNAME)
#define SDKL_PROGNAME		"sdkl"
#endif

#if !defined(SDKL_INIT_VAR)
#define SDKL_INIT_VAR		"SDKL_INIT"
#endif

#define SDKL_INITVARVERSION	SDKL_INIT_VAR SDKL_VERSUFFIX


static sdkl_State *globalL = NULL;

static const char *progname = SDKL_PROGNAME;


#if defined(SDKL_USE_POSIX)   /* { */

/*
** Use 'sigaction' when available.
*/
static void setsignal (int sig, void (*handler)(int)) {
  struct sigaction sa;
  sa.sa_handler = handler;
  sa.sa_flags = 0;
  sigemptyset(&sa.sa_mask);  /* do not mask any signal */
  sigaction(sig, &sa, NULL);
}

#else           /* }{ */

#define setsignal            signal

#endif                               /* } */


/*
** Hook set by signal function to stop the interpreter.
*/
static void lstop (sdkl_State *L, sdkl_Debug *ar) {
  (void)ar;  /* unused arg. */
  sdkl_sethook(L, NULL, 0, 0);  /* reset hook */
  sdklL_error(L, "interrupted!");
}


/*
** Function to be called at a C signal. Because a C signal cannot
** just change a SDKL state (as there is no proper synchronization),
** this function only sets a hook that, when called, will stop the
** interpreter.
*/
static void laction (int i) {
  int flag = SDKL_MASKCALL | SDKL_MASKRET | SDKL_MASKLINE | SDKL_MASKCOUNT;
  setsignal(i, SIG_DFL); /* if another SIGINT happens, terminate process */
  sdkl_sethook(globalL, lstop, flag, 1);
}


static void print_usage (const char *badoption) {
  sdkl_writestringerror("%s: ", progname);
  if (badoption[1] == 'e' || badoption[1] == 'l')
    sdkl_writestringerror("'%s' needs argument\n", badoption);
  else
    sdkl_writestringerror("unrecognized option '%s'\n", badoption);
  sdkl_writestringerror(
  "usage: %s [options] [script [args]]\n"
  "Available options are:\n"
  "  -e stat  execute string 'stat'\n"
  "  -i       enter interactive mode after executing 'script'\n"
  "  -l name  require library 'name' into global 'name'\n"
  "  -v       show version information\n"
  "  -E       ignore environment variables\n"
  "  -W       turn warnings on\n"
  "  --       stop handling options\n"
  "  -        stop handling options and execute stdin\n"
  ,
  progname);
}


/*
** Prints an error message, adding the program name in front of it
** (if present)
*/
static void l_message (const char *pname, const char *msg) {
  if (pname) sdkl_writestringerror("%s: ", pname);
  sdkl_writestringerror("%s\n", msg);
}


/*
** Check whether 'status' is not OK and, if so, prints the error
** message on the top of the stack. It assumes that the error object
** is a string, as it was either generated by SDKL or by 'msghandler'.
*/
static int report (sdkl_State *L, int status) {
  if (status != SDKL_OK) {
    const char *msg = sdkl_tostring(L, -1);
    l_message(progname, msg);
    sdkl_pop(L, 1);  /* remove message */
  }
  return status;
}


/*
** Message handler used to run all chunks
*/
static int msghandler (sdkl_State *L) {
  const char *msg = sdkl_tostring(L, 1);
  if (msg == NULL) {  /* is error object not a string? */
    if (sdklL_callmeta(L, 1, "__tostring") &&  /* does it have a metamethod */
        sdkl_type(L, -1) == SDKL_TSTRING)  /* that produces a string? */
      return 1;  /* that is the message */
    else
      msg = sdkl_pushfstring(L, "(error object is a %s value)",
                               sdklL_typename(L, 1));
  }
  sdklL_traceback(L, L, msg, 1);  /* append a standard traceback */
  return 1;  /* return the traceback */
}


/*
** Interface to 'sdkl_pcall', which sets appropriate message function
** and C-signal handler. Used to run all chunks.
*/
static int docall (sdkl_State *L, int narg, int nres) {
  int status;
  int base = sdkl_gettop(L) - narg;  /* function index */
  sdkl_pushcfunction(L, msghandler);  /* push message handler */
  sdkl_insert(L, base);  /* put it under function and args */
  globalL = L;  /* to be available to 'laction' */
  setsignal(SIGINT, laction);  /* set C-signal handler */
  status = sdkl_pcall(L, narg, nres, base);
  setsignal(SIGINT, SIG_DFL); /* reset C-signal handler */
  sdkl_remove(L, base);  /* remove message handler from the stack */
  return status;
}


static void print_version (void) {
  sdkl_writestring(SDKL_COPYRIGHT, strlen(SDKL_COPYRIGHT));
  sdkl_writeline();
}


/*
** Create the 'arg' table, which stores all arguments from the
** command line ('argv'). It should be aligned so that, at index 0,
** it has 'argv[script]', which is the script name. The arguments
** to the script (everything after 'script') go to positive indices;
** other arguments (before the script name) go to negative indices.
** If there is no script name, assume interpreter's name as base.
*/
static void createargtable (sdkl_State *L, char **argv, int argc, int script) {
  int i, narg;
  if (script == argc) script = 0;  /* no script name? */
  narg = argc - (script + 1);  /* number of positive indices */
  sdkl_createtable(L, narg, script + 1);
  for (i = 0; i < argc; i++) {
    sdkl_pushstring(L, argv[i]);
    sdkl_rawseti(L, -2, i - script);
  }
  sdkl_setglobal(L, "arg");
}


static int dochunk (sdkl_State *L, int status) {
  if (status == SDKL_OK) status = docall(L, 0, 0);
  return report(L, status);
}


static int dofile (sdkl_State *L, const char *name) {
  return dochunk(L, sdklL_loadfile(L, name));
}


static int dostring (sdkl_State *L, const char *s, const char *name) {
  return dochunk(L, sdklL_loadbuffer(L, s, strlen(s), name));
}


/*
** Calls 'require(name)' and stores the result in a global variable
** with the given name.
*/
static int dolibrary (sdkl_State *L, const char *name) {
  int status;
  sdkl_getglobal(L, "require");
  sdkl_pushstring(L, name);
  status = docall(L, 1, 1);  /* call 'require(name)' */
  if (status == SDKL_OK)
    sdkl_setglobal(L, name);  /* global[name] = require return */
  return report(L, status);
}


/*
** Push on the stack the contents of table 'arg' from 1 to #arg
*/
static int pushargs (sdkl_State *L) {
  int i, n;
  if (sdkl_getglobal(L, "arg") != SDKL_TTABLE)
    sdklL_error(L, "'arg' is not a table");
  n = (int)sdklL_len(L, -1);
  sdklL_checkstack(L, n + 3, "too many arguments to script");
  for (i = 1; i <= n; i++)
    sdkl_rawgeti(L, -i, i);
  sdkl_remove(L, -i);  /* remove table from the stack */
  return n;
}


static int handle_script (sdkl_State *L, char **argv) {
  int status;
  const char *fname = argv[0];
  if (strcmp(fname, "-") == 0 && strcmp(argv[-1], "--") != 0)
    fname = NULL;  /* stdin */
  status = sdklL_loadfile(L, fname);
  if (status == SDKL_OK) {
    int n = pushargs(L);  /* push arguments to script */
    status = docall(L, n, SDKL_MULTRET);
  }
  return report(L, status);
}


/* bits of various argument indicators in 'args' */
#define has_error	1	/* bad option */
#define has_i		2	/* -i */
#define has_v		4	/* -v */
#define has_e		8	/* -e */
#define has_E		16	/* -E */


/*
** Traverses all arguments from 'argv', returning a mask with those
** needed before running any SDKL code (or an error code if it finds
** any invalid argument). 'first' returns the first not-handled argument
** (either the script name or a bad argument in case of error).
*/
static int collectargs (char **argv, int *first) {
  int args = 0;
  int i;
  for (i = 1; argv[i] != NULL; i++) {
    *first = i;
    if (argv[i][0] != '-')  /* not an option? */
        return args;  /* stop handling options */
    switch (argv[i][1]) {  /* else check option */
      case '-':  /* '--' */
        if (argv[i][2] != '\0')  /* extra characters after '--'? */
          return has_error;  /* invalid option */
        *first = i + 1;
        return args;
      case '\0':  /* '-' */
        return args;  /* script "name" is '-' */
      case 'E':
        if (argv[i][2] != '\0')  /* extra characters? */
          return has_error;  /* invalid option */
        args |= has_E;
        break;
      case 'W':
        if (argv[i][2] != '\0')  /* extra characters? */
          return has_error;  /* invalid option */
        break;
      case 'i':
        args |= has_i;  /* (-i implies -v) *//* FALLTHROUGH */
      case 'v':
        if (argv[i][2] != '\0')  /* extra characters? */
          return has_error;  /* invalid option */
        args |= has_v;
        break;
      case 'e':
        args |= has_e;  /* FALLTHROUGH */
      case 'l':  /* both options need an argument */
        if (argv[i][2] == '\0') {  /* no concatenated argument? */
          i++;  /* try next 'argv' */
          if (argv[i] == NULL || argv[i][0] == '-')
            return has_error;  /* no next argument or it is another option */
        }
        break;
      default:  /* invalid option */
        return has_error;
    }
  }
  *first = i;  /* no script name */
  return args;
}


/*
** Processes options 'e' and 'l', which involve running SDKL code, and
** 'W', which also affects the state.
** Returns 0 if some code raises an error.
*/
static int runargs (sdkl_State *L, char **argv, int n) {
  int i;
  for (i = 1; i < n; i++) {
    int option = argv[i][1];
    sdkl_assert(argv[i][0] == '-');  /* already checked */
    switch (option) {
      case 'e':  case 'l': {
        int status;
        const char *extra = argv[i] + 2;  /* both options need an argument */
        if (*extra == '\0') extra = argv[++i];
        sdkl_assert(extra != NULL);
        status = (option == 'e')
                 ? dostring(L, extra, "=(command line)")
                 : dolibrary(L, extra);
        if (status != SDKL_OK) return 0;
        break;
      }
      case 'W':
        sdkl_warning(L, "@on", 0);  /* warnings on */
        break;
    }
  }
  return 1;
}


static int handle_sdklinit (sdkl_State *L) {
  const char *name = "=" SDKL_INITVARVERSION;
  const char *init = getenv(name + 1);
  if (init == NULL) {
    name = "=" SDKL_INIT_VAR;
    init = getenv(name + 1);  /* try alternative name */
  }
  if (init == NULL) return SDKL_OK;
  else if (init[0] == '@')
    return dofile(L, init+1);
  else
    return dostring(L, init, name);
}


/*
** {==================================================================
** Read-Eval-Print Loop (REPL)
** ===================================================================
*/

#if !defined(SDKL_PROMPT)
#define SDKL_PROMPT		"> "
#define SDKL_PROMPT2		">> "
#endif

#if !defined(SDKL_MAXINPUT)
#define SDKL_MAXINPUT		512
#endif


/*
** sdkl_stdin_is_tty detects whether the standard input is a 'tty' (that
** is, whether we're running sdkl interactively).
*/
#if !defined(sdkl_stdin_is_tty)	/* { */

#if defined(SDKL_USE_POSIX)	/* { */

#include <unistd.h>
#define sdkl_stdin_is_tty()	isatty(0)

#elif defined(SDKL_USE_WINDOWS)	/* }{ */

#include <io.h>
#include <windows.h>

#define sdkl_stdin_is_tty()	_isatty(_fileno(stdin))

#else				/* }{ */

/* ISO C definition */
#define sdkl_stdin_is_tty()	1  /* assume stdin is a tty */

#endif				/* } */

#endif				/* } */


/*
** sdkl_readline defines how to show a prompt and then read a line from
** the standard input.
** sdkl_saveline defines how to "save" a read line in a "history".
** sdkl_freeline defines how to free a line read by sdkl_readline.
*/
#if !defined(sdkl_readline)	/* { */

#if defined(SDKL_USE_READLINE)	/* { */

#include <readline/readline.h>
#include <readline/history.h>
#define sdkl_initreadline(L)	((void)L, rl_readline_name="sdkl")
#define sdkl_readline(L,b,p)	((void)L, ((b)=readline(p)) != NULL)
#define sdkl_saveline(L,line)	((void)L, add_history(line))
#define sdkl_freeline(L,b)	((void)L, free(b))

#else				/* }{ */

#define sdkl_initreadline(L)  ((void)L)
#define sdkl_readline(L,b,p) \
        ((void)L, fputs(p, stdout), fflush(stdout),  /* show prompt */ \
        fgets(b, SDKL_MAXINPUT, stdin) != NULL)  /* get line */
#define sdkl_saveline(L,line)	{ (void)L; (void)line; }
#define sdkl_freeline(L,b)	{ (void)L; (void)b; }

#endif				/* } */

#endif				/* } */


/*
** Return the string to be used as a prompt by the interpreter. Leave
** the string (or nil, if using the default value) on the stack, to keep
** it anchored.
*/
static const char *get_prompt (sdkl_State *L, int firstline) {
  if (sdkl_getglobal(L, firstline ? "_PROMPT" : "_PROMPT2") == SDKL_TNIL)
    return (firstline ? SDKL_PROMPT : SDKL_PROMPT2);  /* use the default */
  else {  /* apply 'tostring' over the value */
    const char *p = sdklL_tolstring(L, -1, NULL);
    sdkl_remove(L, -2);  /* remove original value */
    return p;
  }
}

/* mark in error messages for incomplete statements */
#define EOFMARK		"<EOF>"
#define marklen		(sizeof(EOFMARK)/sizeof(char) - 1)


/*
** Check whether 'status' signals a syntax error and the error
** message at the top of the stack ends with the above mark for
** incomplete statements.
*/
static int incomplete (sdkl_State *L, int status) {
  if (status == SDKL_ERRSYNTAX) {
    size_t lmsg;
    const char *msg = sdkl_tolstring(L, -1, &lmsg);
    if (lmsg >= marklen && strcmp(msg + lmsg - marklen, EOFMARK) == 0) {
      sdkl_pop(L, 1);
      return 1;
    }
  }
  return 0;  /* else... */
}


/*
** Prompt the user, read a line, and push it into the SDKL stack.
*/
static int pushline (sdkl_State *L, int firstline) {
  char buffer[SDKL_MAXINPUT];
  char *b = buffer;
  size_t l;
  const char *prmt = get_prompt(L, firstline);
  int readstatus = sdkl_readline(L, b, prmt);
  if (readstatus == 0)
    return 0;  /* no input (prompt will be popped by caller) */
  sdkl_pop(L, 1);  /* remove prompt */
  l = strlen(b);
  if (l > 0 && b[l-1] == '\n')  /* line ends with newline? */
    b[--l] = '\0';  /* remove it */
  if (firstline && b[0] == '=')  /* for compatibility with 5.2, ... */
    sdkl_pushfstring(L, "return %s", b + 1);  /* change '=' to 'return' */
  else
    sdkl_pushlstring(L, b, l);
  sdkl_freeline(L, b);
  return 1;
}


/*
** Try to compile line on the stack as 'return <line>;'; on return, stack
** has either compiled chunk or original line (if compilation failed).
*/
static int addreturn (sdkl_State *L) {
  const char *line = sdkl_tostring(L, -1);  /* original line */
  const char *retline = sdkl_pushfstring(L, "return %s;", line);
  int status = sdklL_loadbuffer(L, retline, strlen(retline), "=stdin");
  if (status == SDKL_OK) {
    sdkl_remove(L, -2);  /* remove modified line */
    if (line[0] != '\0')  /* non empty? */
      sdkl_saveline(L, line);  /* keep history */
  }
  else
    sdkl_pop(L, 2);  /* pop result from 'sdklL_loadbuffer' and modified line */
  return status;
}


/*
** Read multiple lines until a complete SDKL statement
*/
static int multiline (sdkl_State *L) {
  for (;;) {  /* repeat until gets a complete statement */
    size_t len;
    const char *line = sdkl_tolstring(L, 1, &len);  /* get what it has */
    int status = sdklL_loadbuffer(L, line, len, "=stdin");  /* try it */
    if (!incomplete(L, status) || !pushline(L, 0)) {
      sdkl_saveline(L, line);  /* keep history */
      return status;  /* cannot or should not try to add continuation line */
    }
    sdkl_pushliteral(L, "\n");  /* add newline... */
    sdkl_insert(L, -2);  /* ...between the two lines */
    sdkl_concat(L, 3);  /* join them */
  }
}


/*
** Read a line and try to load (compile) it first as an expression (by
** adding "return " in front of it) and second as a statement. Return
** the final status of load/call with the resulting function (if any)
** in the top of the stack.
*/
static int loadline (sdkl_State *L) {
  int status;
  sdkl_settop(L, 0);
  if (!pushline(L, 1))
    return -1;  /* no input */
  if ((status = addreturn(L)) != SDKL_OK)  /* 'return ...' did not work? */
    status = multiline(L);  /* try as command, maybe with continuation lines */
  sdkl_remove(L, 1);  /* remove line from the stack */
  sdkl_assert(sdkl_gettop(L) == 1);
  return status;
}


/*
** Prints (calling the SDKL 'print' function) any values on the stack
*/
static void l_print (sdkl_State *L) {
  int n = sdkl_gettop(L);
  if (n > 0) {  /* any result to be printed? */
    sdklL_checkstack(L, SDKL_MINSTACK, "too many results to print");
    sdkl_getglobal(L, "print");
    sdkl_insert(L, 1);
    if (sdkl_pcall(L, n, 0, 0) != SDKL_OK)
      l_message(progname, sdkl_pushfstring(L, "error calling 'print' (%s)",
                                             sdkl_tostring(L, -1)));
  }
}


/*
** Do the REPL: repeatedly read (load) a line, evasdklte (call) it, and
** print any results.
*/
static void doREPL (sdkl_State *L) {
  int status;
  const char *oldprogname = progname;
  progname = NULL;  /* no 'progname' on errors in interactive mode */
  sdkl_initreadline(L);
  while ((status = loadline(L)) != -1) {
    if (status == SDKL_OK)
      status = docall(L, 0, SDKL_MULTRET);
    if (status == SDKL_OK) l_print(L);
    else report(L, status);
  }
  sdkl_settop(L, 0);  /* clear stack */
  sdkl_writeline();
  progname = oldprogname;
}

/* }================================================================== */


/*
** Main body of stand-alone interpreter (to be called in protected mode).
** Reads the options and handles them all.
*/
static int pmain (sdkl_State *L) {
  int argc = (int)sdkl_tointeger(L, 1);
  char **argv = (char **)sdkl_touserdata(L, 2);
  int script;
  int args = collectargs(argv, &script);
  sdklL_checkversion(L);  /* check that interpreter has correct version */
  if (argv[0] && argv[0][0]) progname = argv[0];
  if (args == has_error) {  /* bad arg? */
    print_usage(argv[script]);  /* 'script' has index of bad arg. */
    return 0;
  }
  if (args & has_v)  /* option '-v'? */
    print_version();
  if (args & has_E) {  /* option '-E'? */
    sdkl_pushboolean(L, 1);  /* signal for libraries to ignore env. vars. */
    sdkl_setfield(L, SDKL_REGISTRYINDEX, "SDKL_NOENV");
  }
  sdklL_openlibs(L);  /* open standard libraries */
  createargtable(L, argv, argc, script);  /* create table 'arg' */
  sdkl_gc(L, SDKL_GCGEN, 0, 0);  /* GC in generational mode */
  if (!(args & has_E)) {  /* no option '-E'? */
    if (handle_sdklinit(L) != SDKL_OK)  /* run SDKL_INIT */
      return 0;  /* error running SDKL_INIT */
  }
  if (!runargs(L, argv, script))  /* execute arguments -e and -l */
    return 0;  /* something failed */
  if (script < argc &&  /* execute main script (if there is one) */
      handle_script(L, argv + script) != SDKL_OK)
    return 0;
  if (args & has_i)  /* -i option? */
    doREPL(L);  /* do read-eval-print loop */
  else if (script == argc && !(args & (has_e | has_v))) {  /* no arguments? */
    if (sdkl_stdin_is_tty()) {  /* running in interactive mode? */
      print_version();
      doREPL(L);  /* do read-eval-print loop */
    }
    else dofile(L, NULL);  /* executes stdin as a file */
  }
  sdkl_pushboolean(L, 1);  /* signal no errors */
  return 1;
}


int main (int argc, char **argv) {
  int status, result;
  sdkl_State *L = sdklL_newstate();  /* create state */
  if (L == NULL) {
    l_message(argv[0], "cannot create state: not enough memory");
    return EXIT_FAILURE;
  }
  sdkl_pushcfunction(L, &pmain);  /* to call 'pmain' in protected mode */
  sdkl_pushinteger(L, argc);  /* 1st argument */
  sdkl_pushlightuserdata(L, argv); /* 2nd argument */
  status = sdkl_pcall(L, 2, 1, 0);  /* do the call */
  result = sdkl_toboolean(L, -1);  /* get result */
  report(L, status);
  sdkl_close(L);
  return (result && status == SDKL_OK) ? EXIT_SUCCESS : EXIT_FAILURE;
}

